baseURL = 'https://ignativssss.com/'
languageCode = 'zh-cn'
title = 'è±šéª¨æ‹‰é¢é¦†ğŸœ'
theme = "PaperMod"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
avatar = "ğŸœ"
name = "è±šéª¨æ‹‰é¢é¦†é¦†é•¿"
bio = "æ‚é£Ÿå®¶æ”¿å¥³ç‹ï¼Œçˆ±é€›è¶…å¸‚"
busuanzi = {enable = true}

[menu]
  [[menu.main]]
    identifier = "home"
    name = "é¦–é¡µ"
    url = "/"
    weight = 1

    # å­èœå•é¡¹ - ç¤ºä¾‹çš„æ ‡ç­¾æˆ–åˆ†ç±»
    [[menu.main]]
      parent = "home"   # è®¾ç½®ä¸ºé¦–é¡µçš„å­èœå•
      identifier = "å¨æˆ¿æ•…äº‹"
      name = "å¨æˆ¿æ•…äº‹"
      url = "/tags/å¨æˆ¿æ•…äº‹/"
      weight = 1

    [[menu.main]]
      parent = "home"
      identifier = "ç”Ÿæ´»æ‚è®°"
      name = "ç”Ÿæ´»æ‚è®°"
      url = "/tags/ç”Ÿæ´»æ‚è®°/"
      weight = 2

    [[menu.main]]
      parent = "home"
      identifier = "æœˆåº¦è¯»ä¹¦"
      name = "æœˆåº¦è¯»ä¹¦"
      url = "/tags/æœˆåº¦è¯»ä¹¦/"
      weight = 3

    [[menu.main]]
      parent = "home"
      identifier = "ä¹°ä¹°ä¹°"
      name = "ä¹°ä¹°ä¹°"
      url = "/tags/ä¹°ä¹°ä¹°/"
      weight = 4
      
  [[menu.main]]
    identifier = "archives"
    name = "å½’æ¡£"
    url = "/archives/"
    weight = 2

  [[menu.main]]
    identifier = "tags"
    name = "æ ‡ç­¾"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "å…³äºæˆ‘"
    url = "/about/"
    weight = 4

  [[menu.main]]
    identifier = "friends"
    name = "å‹é“¾"
    url = "/friends/"
    weight = 5

  [[menu.main]]
    identifier = "search"
    name = "æœç´¢"
    url = "/search/"
    weight = 6

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = ["lastmod", ":fileModTime", "date"]